#!/bin/bash

action=$1
message=$2
date=$3
shift

[ "$action" = "usage" ] && {
  echo "  $(basename $0) \"THING I DID +project @context\" \"Repeat interval\""
  echo "    Add and repeat:"
  echo "    Add an item and add it to repeat.txt at interval"
  echo ""
  exit
}

if "$TODO_SH" command add "$message"; then
    "$TODO_SH" -T command addto repeat.txt "$message repeat:$date"
fi
