#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  $(basename $0) \"THING I DID +project @context\""
  echo "    Add and do:"
  echo "    Add an item and mark it as done in one step"
  echo ""
  exit
}

if "$TODO_SH" command add "$@"; then
    # figure out the line of what we just added, and prioritize it A
    line=`sed -n '$ =' "$TODO_FILE"`
    echo "$line"
    "$TODO_SH" command do "$line"
fi
