#!/bin/bash

function usage() {
  echo "  $(basename $0) ITEM# [TERM]"
  echo "    Deletes the task on line ITEM# in repeat.txt"
  echo "    If TERM specified, deletes only TERM from the task."
  echo ""
  exit
}

action=$1
shift

[ "$action" = "usage" ] && {
    usage
}

TODO_REPEAT_FILE=$TODO_DIR/repeat.txt

# replace deleted line with a blank line when TODOTXT_PRESERVE_LINE_NUMBERS is 1
item=$1
[ -z "$item" ] && usage
[[ "$item" = +([0-9]) ]] || usage
DELETEME=$(sed "$item!d" "$TODO_REPEAT_FILE")
[ -z "$DELETEME" ] && die "TODO: No task $item."

if [ -z "$3" ]; then
    if  [ $TODOTXT_FORCE = 0 ]; then
        echo "Delete '$DELETEME'?  (y/n)"
        read ANSWER
    else
        ANSWER="y"
    fi
    if [ "$ANSWER" = "y" ]; then
        if [ $TODOTXT_PRESERVE_LINE_NUMBERS = 0 ]; then
            # delete line (changes line numbers)
            sed -i.bak -e $item"s/^.*//" -e '/./!d' "$TODO_REPEAT_FILE"
        else
            # leave blank line behind (preserves line numbers)
            sed -i.bak -e $item"s/^.*//" "$TODO_REPEAT_FILE"
        fi
        if [ $TODOTXT_VERBOSE -gt 0 ]; then
            echo "$item $DELETEME"
            echo "TODO: $item deleted."
        fi
    else
        echo "TODO: No tasks were deleted."
    fi
else
    sed -i.bak \
        -e $item"s/^\((.) \)\{0,1\} *$3 */\1/g" \
        -e $item"s/ *$3 *\$//g" \
        -e $item"s/  *$3 */ /g" \
        -e $item"s/ *$3  */ /g" \
        -e $item"s/$3//g" \
        "$TODO_REPEAT_FILE"
    newtodo=$(sed "$item!d" "$TODO_REPEAT_FILE")
    if [ "$DELETEME" = "$newtodo" ]; then
        [ $TODOTXT_VERBOSE -gt 0 ] && echo "$item $DELETEME"
        die "TODO: '$3' not found; no removal done."
    fi
    if [ $TODOTXT_VERBOSE -gt 0 ]; then
        echo "$item $DELETEME"
        echo "TODO: Removed '$3' from task."
        echo "$item $newtodo"
    fi
fi
